//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairPlayBudget.AutomatedTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FairPlayBudget.AutomatedTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref,Fecha,Tipo,Establecimiento,Monto,Moneda
        ///123,15/12/2023,COMPRAS,Fresh Market,123,Colones
        ///123,23/12/2023,PAGOS,DBT CTA,-234,Dólares.
        /// </summary>
        public static string CreditTransactionsFileTemplate {
            get {
                return ResourceManager.GetString("CreditTransactionsFileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Post-Deployment Script Template							
        ///--------------------------------------------------------------------------------------
        /// This file contains SQL statements that will be appended to the build script.		
        /// Use SQLCMD syntax to include a file in the post-deployment script.			
        /// Example:      :r .\myfile.sql								
        /// Use SQLCMD syntax to reference a variable in the post-deployment script.		
        /// Example:      :setvar TableName MyTable							
        ///               SELECT * FROM [$(TableName)]					
        ///----------- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SeedData {
            get {
                return ResourceManager.GetString("SeedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oficina;fechaMovimiento;numeroDocumento;debito;credito;descripcion;
        ///123;10/12/2023;999;12;;Confites Prueb;
        ///123;10/12/2023;999;;14;Confites Prueb;
        ///123;10/12/2023;999;45;;Confites Prueb;
        ///123;10/12/2023;999;;90;Confites Prueb;
        ///123;10/12/2023;999;45;;Confites Prueb;.
        /// </summary>
        public static string TransactionsFileTemplate {
            get {
                return ResourceManager.GetString("TransactionsFileTemplate", resourceCulture);
            }
        }
    }
}
