// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayBudget.DataAccess.Models;

public partial class Currency
{
    [Key]
    public int CurrencyId { get; set; }

    [Required]
    [StringLength(50)]
    public string Description { get; set; }

    [InverseProperty("Currency")]
    public virtual ICollection<Expense> Expense { get; set; } = new List<Expense>();

    [InverseProperty("Currency")]
    public virtual ICollection<Income> Income { get; set; } = new List<Income>();
}