// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayBudget.DataAccess.Models;

public partial class Expense
{
    [Key]
    public long ExpenseId { get; set; }

    public DateTimeOffset ExpenseDateTime { get; set; }

    [Required]
    [StringLength(50)]
    public string Description { get; set; }

    [Column("AmountInUSD", TypeName = "money")]
    public decimal AmountInUsd { get; set; }

    [Required]
    [StringLength(450)]
    public string OwnerId { get; set; }

    [ForeignKey("OwnerId")]
    [InverseProperty("Expense")]
    public virtual AspNetUsers Owner { get; set; }
}