// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayBudget.DataAccess.Models;

[Keyless]
public partial class VwBalance
{
    [Required]
    [StringLength(450)]
    public string OwnerId { get; set; }

    [Column(TypeName = "money")]
    public decimal Amount { get; set; }

    [StringLength(10)]
    public string TransactionType { get; set; }

    public DateTimeOffset DateTime { get; set; }

    [Required]
    [StringLength(50)]
    public string Description { get; set; }

    public int CurrencyId { get; set; }

    [Required]
    [StringLength(50)]
    public string Currency { get; set; }

    [StringLength(150)]
    public string MonthlyBudgetDescription { get; set; }
}